name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Publish to Registry
      run: docker build . --file Dockerfile --tag docker-api
    
    - name: login to docker
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-sdtin
    
    - name: push to docker hub
      run: docker push idirall22/docker_test:docker-api
    
